### PR TITLE
Linux: Convert spec file back to Unix-like LF endings

### PR DESCRIPTION
**Pull request by Thaodan**
Fixes: 75f2f87f552df51a4d679adb753167b169b629fe

### CODE REVIEW

**Comment by Thaodan** [comment]
Also bring back changelog and convert to OpenSUSE format which it already mostly was in.

**Comment by Thaodan** [comment]
Also cleanup minor errors in the spec file as suggested by rpmlint.

The only bigger error remaining as noted by rpmlint is this one:
```
[   15s] davmail.noarch: W: class-path-in-manifest /usr/share/davmail/davmail.jar
[   15s] The META-INF/MANIFEST.MF file in the jar contains a hardcoded Class-Path.
[   15s] These entries do not work with older Java versions and even if they do work,
[   15s] they are inflexible and usually cause nasty surprises.
```

**Comment by mguessan** [comment]
Changes merged in trunk

**Comment by Thaodan** [comment]
> Changes merged in trunk

Can you stop removing the commit author? 

Also the changes were not merged, you just restore the spec file but without my changes.

**Comment by Thaodan** [comment]
Also the changelog is still embedded in the spec file which is wrong.

**Comment by mguessan** [comment]
Reopening, don't want to hide your contribution, I still commit on sourceforge and then sync to github... I know outdated workflow.

Anyway still need to fix multiple things it seems.

**Comment by Thaodan** [comment]
Are you using svn directly? Maybe there's some svn->git extension so you
can keep using svn even out Github.

**Comment by mguessan** [comment]
> Are you using svn directly? Maybe there's some svn->git extension so you can keep using svn even out Github.

Well I currently use git svn to synchronize both, if at some point I drop svn repo I will just switch to full git workflow. This project is more than 20 years old... initially developed before Exchange 2000.

**Comment by Thaodan** [comment]
Why do you keep the svn repo then?

**Comment by mguessan** [comment]
Used to be that Sourceforge was the main DavMail site and Github just an additional sync for visibility and integration with AppVeyor, Travis-CI, now most activity has moved to Github but release process is still tied to svn (e.g. svn commit number).

Anyway, back to your pull request I tried to take into account your commits: moved changelog to separate file, some spec file cleanup and also removed reference to svn commit number there.

I will to a full release soon to publish important updates and validate everything still working as expected.

**Comment by mguessan** [comment]
Still stuck to svn based workflow, however removed the svn commit dependency to make release process simpler.

Please review latest 6.2.1 for any additional issues

**Pull request closed without merging**
