### PR TITLE
persist refresh token

### PR DESCRIPTION
**Pull request by piyushgarg**
#211 
With this fix, the refresh token will be updated and stored during load and during expiry of access token.

### CODE REVIEW

**Comment by cwarden** [comment]
This does cause a new refresh token to be stored, but doesn't necessarily solve the problem with refresh token expiration.  I get
```
2022-10-10 19:08:15,389 ERROR [PopConnection-37050] davmail.exchange.auth.O365Token  - refresh token failed
java.io.IOException: interaction_required AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2022-10-03T21:27:16.1016650Z and the maximum allowed lifetime for this request is 604800.
```
It likes like the new refresh tokens maintain the expiration date of the original refresh token.  I found documentation that a [Sign-in Frequency setting](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-session) drives this expiration.

It would be helpful if davmail had a way of calling a program when it needs a new refresh token, or a way of providing it a new refresh token (through a custom IMAP command maybe?).

**Comment by piyushgarg** [comment]
As per the [spec](https://learn.microsoft.com/en-us/advertising/guides/authentication-oauth-get-tokens)

> Refresh tokens are, and always will be, completely opaque to your application. They are long-lived e.g., 90 days for public clients, but the app should not be written to expect that a refresh token will last for any period of time.

**Comment by tmcqueen-materials** [comment]
@mguessan : Just want to upvote inclusion of the feature to update the refresh token when included with refreshed access tokens. the [OAuth 2 spec](https://tools.ietf.org/html/rfc6749#section-6) states that "[t]he authorization server MAY issue a new refresh token, in which case the client MUST discard the old refresh token and replace it with the new refresh token. The authorization server MAY revoke the old refresh token after issuing a new refresh token to the client."

So this feature (or some equivalent) needs to be included for davmail to be spec-compliant. Further, given Microsoft's wording at [Get access and refresh tokens](https://learn.microsoft.com/en-us/advertising/guides/authentication-oauth-get-tokens), they may be choosing at some point in the near future to in fact actually revoke old refresh tokens before expiry, which, in the absence of this feature, will generate many more sign-in flows.

**Comment by mguessan** [comment]
I took a slightly different approach than this pull request: make sure the password is always provided to O365Token so it's easy to encrypt/decrypt token.

Can someone please check latest build to confirm it's working as expected ?

**Comment by tmcqueen-materials** [comment]
@mguessan : I have had it running for a few hours now, along with several restarts, and it looks to be properly updating the refresh tokens in storage, but I won't know for sure until I've waited long enough to know the older refresh tokens have expired. Thanks again for looking at this!

**Comment by peterhoeg** [comment]
I may be going slightly off-topic here but is there a way the token could be stored separately from the main configuration file? If one is using davmail where the configuration file is generated and stored read-only (because nothing else should change in this file anyway), it will obvoiusly fail when trying to write back the token.

**Comment by mguessan** [comment]
@peterhoeg please try the experimental davmail.oauth.tokenFilePath setting to store token in a separate file

**Comment by peterhoeg** [comment]
I'll check it out this weekend, thank you!

In the mean time I've worked around it by generating the read-only part and then have a script run that merges the read-only bit with the token and then pass *that* file to davmail. 

When the token is updated, I still need to move it into the .creds file manually, but at least I can still generate the configuration.

**Comment by peterhoeg** [comment]
@mguessan , `tokenFilePath` works wonderfully!!

**Pull request closed without merging**
