### PR TITLE
desktop file: remove deprecations and duplicate main categories

### PR DESCRIPTION
**Pull request by wberrier**
To satisfy desktop-file-validate

Modeled after the debian desktop file in build.xml

### CODE REVIEW

**Comment by mguessan** [comment]
Interesting, I would like to have a single desktop file instead of:
- RPM contribs
- Debian package from trunk build
- Official debian package, see https://salsa.debian.org/debian/davmail/blob/master/debian/davmail.desktop

A few questions:
- should Icon be an absolute path or not ?
- is debian Categories fine or should we use only Network ?

**Comment by wberrier** [comment]
> Interesting, I would like to have a single desktop file instead of:

What do you suggest?  I could:

* remove ./davmail.desktop (not sure who uses this one?)
* update the rpm contrib version to pass validation
* have the dpkg build.xml version use the rpm contrib version

Does this go along with what you were thinking?

> should Icon be an absolute path or not ?

From the xdg spec, it can be either:

> Icon to display in file manager, menus, etc. If the name is an absolute path, the given file will be used. If the name is not an absolute path, the algorithm described in the Icon Theme Specification will be used to locate the icon.

The algorithm allows shipping and displaying icons of various sizes.

> is debian Categories fine or should we use only Network ?

I think the debian categories are fine.  The issue with the rpm contrib categories is that it included multiple "main" categories:

https://standards.freedesktop.org/menu-spec/latest/apa.html

`desktop-file-validate` was warning that the multiple categories may cause launchers to be created in multiple places.

Also, another sorta related item is multiple shell wrapper scripts:

* src/contribs/rpm/SOURCES/davmail.sh
* src/bin/davmail
* davmail.sh

but maybe that would be out of scope for this pull request.

**Comment by mguessan** [comment]
Ok, made some progress:
- removed ./davmail.desktop (was included in deprecated linux packages)
- dropped Debian desktop file generation and moved desktop file to src/desktop
- use logical instead of path for icon
- merged RPM and Debian desktop file (still keep one under contribs for RPM users)

About shell scripts: I do agree this could be improved. ./davmail.sh is included in platform independent package, src/bin/davmail is my Debian shell script and the one under rpm is a user contribution.

**Comment by wberrier** [comment]
Great, thanks!

**Comment by wberrier** [comment]
Great, thanks!

**Comment by mguessan** [comment]
Had to change categories again, was rejected by OpenSuse, see:
https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories

New category would be:
Categories=GTK;GNOME;Network;Email;

**Comment by wberrier** [comment]
Sounds good to me, I think that should be fine.

**Pull request closed without merging**
