### PR TITLE
Add davmail.disableTrayActivitySwitch to disable tray icon activity

### LINKED ISSUE #24: Disable tray icon flashing
Hello,
Is there a way to disable the flashing of the icon in the tray bar ?
I find it very distracting.

I tried the -notray parameter, but i would prefer to keep the icon in the tray, just without flashing.

I am using ubuntu 16.04

### PR DESCRIPTION
**Pull request by knixeur**
This disables icon switching while there's activity in davmail.
It introduces a new setting variable ```davmail.disableTrayActivitySwitch=false``` off by default.
It can also be changed using GUI settings which reads by default `Disable tray icon activity`

screenshot-20190514 123107

Hope it helps, thanks for making davmail!

Fixes #24

Edit: By the way, just to let you know, I made this patch against 5.2.0 tag because master isn't working with OWA 2010 (at least at my company), if I have some time another day I'll try to debug it but I know you're currently working with new auth schemes.

### CODE REVIEW

**Comment by knixeur** [comment]
I've just fixed the settings panel, I forgot to increment grid's rows count.

**Comment by mguessan** [comment]
Thanks for your contribution, can you please provide more information on your issue with latest trunk ?

**Comment by knixeur** [comment]
Sure, it fails to authenticate, I don't know if there's a .log file so I'm copying LogFactor5's relevant output here:
```
Date:			Tue May 14 12:02:01 ART 2019 (1557846121246)
Thread:		ImapConnection-34366
Message #:	31
Level:		DEBUG
NDC:			
Category:	davmail.exchange.ExchangeSession
Message:		OWA authentication in EWS mode
Location:	davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:189)
Thrown:
```

```
Date:			Tue May 14 12:02:01 ART 2019 (1557846121337)
Thread:		ImapConnection-34366
Message #:	32
Level:		DEBUG
NDC:			
Category:	davmail.http.DavMailX509KeyManager
Message:		Find client certificates issued by: []
Location:	davmail.http.DavMailX509KeyManager.chooseClientAlias(DavMailX509KeyManager.java:77)
Thrown:
```

```
Date:			Tue May 14 12:02:01 ART 2019 (1557846121339)
Thread:		ImapConnection-34366
Message #:	33
Level:		DEBUG
NDC:			
Category:	davmail.http.DavMailX509KeyManager
Message:		No Private Keys found
Location:	davmail.http.DavMailX509KeyManager.chooseClientAlias(DavMailX509KeyManager.java:157)
Thrown:
```

some redirects...

```
Date:			Tue May 14 12:02:01 ART 2019 (1557846121430)
Thread:		ImapConnection-34366
Message #:	36
Level:		DEBUG
NDC:			
Category:	davmail.exchange.ExchangeSession
Message:		Form based authentication detected
Location:	davmail.exchange.auth.ExchangeFormAuthenticator.formLogin(ExchangeFormAuthenticator.java:288)
Thrown:
```

some redirects...

```
Date:			Tue May 14 12:02:01 ART 2019 (1557846121948)
Thread:		ImapConnection-34366
Message #:	41
Level:		DEBUG
NDC:			
Category:	davmail.exchange.ExchangeSession
Message:		Session davmail.exchange.auth.ExchangeFormAuthenticator@4f16a60 created
Location:	davmail.exchange.auth.ExchangeFormAuthenticator.authenticate(ExchangeFormAuthenticator.java:244)
Thrown:
```

```
Date:			Tue May 14 12:02:01 ART 2019 (1557846121961)
Thread:		ImapConnection-34366
Message #:	42
Level:		WARN
NDC:			
Category:	org.apache.commons.httpclient.HttpMethodDirector
Message:		Unable to respond to any of these challenges: {negotiate=Negotiate, ntlm=NTLM}
Location:	org.apache.commons.httpclient.HttpMethodDirector.processWWWAuthChallenge(HttpMethodDirector.java:697)
Thrown:
```

```
Date:			Tue May 14 12:02:01 ART 2019 (1557846121963)
Thread:		ImapConnection-34366
Message #:	43
Level:		INFO
NDC:			
Category:	davmail.connection
Message:		FAILED - 127.0.0.1:34366 <editedmail>
Location:	davmail.AbstractConnection.logConnection(AbstractConnection.java:158)
Thrown:
```

```
Date:			Tue May 14 12:02:01 ART 2019 (1557846121963)
Thread:		ImapConnection-34366
Message #:	44
Level:		ERROR
NDC:			
Category:	davmail
Message:		Authentication failed: invalid user or password
Location:	davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:114)
Thrown:
davmail.exception.DavMailAuthenticationException: Authentication failed: invalid user or password
	at davmail.exchange.ews.EwsExchangeSession.buildSessionInfo(EwsExchangeSession.java:231)
	at davmail.exchange.ews.EwsExchangeSession.<init>(EwsExchangeSession.java:184)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:196)
	at davmail.exchange.ExchangeSessionFactory.getInstance(ExchangeSessionFactory.java:97)
	at davmail.imap.ImapConnection.run(ImapConnection.java:112)
```

I've this same changes rebased against master to make a new PR if you want I can close this and make the other one, but I cannot test it.

**Comment by mguessan** [comment]
Patch merged, thanks for your contribution.

If you still have the Exchange 2010 issue, please open a separate ticket.
Suggestions: use EWS mode with direct EWS url insteal of OWA entry point.

**Comment by knixeur** [comment]
@mguessan all working fine with master now, thanks! :+1:

**Comment by averter** [comment]
I don't think that this is working as it should. I've ticked the "Disable tray activity switch" and it didn't stop flashing. I'm on version 5.3.0-3065

**Pull request closed without merging**
