### PR TITLE
Fixes #309, timezone offsets can have seconds component

### LINKED ISSUE #309: Timezone offset problem with longer offsets
Issue occurs with latest thunderbird daily. I don't know actually why but thunderbird sends a VCAL like this:

```
BEGIN:VCALENDAR
...
TZOFFSETTO:+010000
TZOFFSETFROM:+012200
DTSTART:18840101T000000
RDATE:18840101T000000
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETTO:+020000
TZOFFSETFROM:+010000

```

According to [RFC](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.14) the last seconds component is optional but can appear. 

When davmail gets such vcal it throws 503 with error in VCalendar.java:396 trying to find the offset in ResourceBundle. 

I have fixed this for me adding to the resourcebundle (tzoffsettimezones.properties) a cloned list with 00 at the end.. 

I will send a PR with this fix.

### PR DESCRIPTION
**Pull request by br0xpl**
Fixes #309 , timezone offsets can have seconds component

### CODE REVIEW

**Comment by esabol** [comment]
@br0xpl : Typo in PR title. Change "compoment" to "component".

**Comment by Kenny2github** [comment]
Thank you with all my heart. This issue has been blocking me from putting my tests in my calendar for days. The user-facing error that this issue causes is also completely opaque - DavMail says `Can't find resource for bundle java.util.PropertyResourceBundle, key` (timezone offset with seconds) for every event created in Thunderbird 115. If you create a bunch of events before the calendar syncs, it gives you a whole bunch of the same notification at once. Hopefully this comment helps someone searching for the same thing.

Building and installing this PR fixed the issue. Steps:
1. Clone and checkout this PR.
2. Follow the build steps here: https://davmail.sourceforge.net/build.html
3. The installers will be built in the `dist` directory - use the one appropriate for your operating system.
4. If creating events works at this point, you're done!
5. If you get a further `ClassNotFoundException`, O365Interactive authentication does not work in your build and you will have to:
  1. Switch to O365Manual instead.
  2. If you are using a `urn:` redirect URI like I was to pretend to be Outlook, when clicking "Continue" to confirm that it is Outlook you will not navigate anywhere but instead your browser will produce a console error containing the URN it was trying to navigate you to. Otherwise look at the URL you were redirected to.
  3. Copy the value of the `?...code=THIS PART` parameter and provide it to DavMail.

**Comment by br0xpl** [comment]
> Thank you with all my heart. This issue has been blocking me from putting my tests in my calendar for days. The user-facing error that this issue causes is also completely opaque - DavMail says `Can't find resource for bundle java.util.PropertyResourceBundle, key` (timezone offset with seconds) for every event created in Thunderbird 115. If you create a bunch of events before the calendar syncs, it gives you a whole bunch of the same notification at once. Hopefully this comment helps someone searching for the same thing.
> 
> Building and installing this PR fixed the issue. Steps:
> 
>     1. Clone and checkout this PR.
> 
>     2. Follow the build steps here: https://davmail.sourceforge.net/build.html
> 
>     3. The installers will be built in the `dist` directory - use the one appropriate for your operating system.
> 
>     4. If creating events works at this point, you're done!
> 
>     5. If you get a further `ClassNotFoundException`, O365Interactive authentication does not work in your build and you will have to:
> 
>     6. Switch to O365Manual instead.
> 
>     7. If you are using a `urn:` redirect URI like I was to pretend to be Outlook, when clicking "Continue" to confirm that it is Outlook you will not navigate anywhere but instead your browser will produce a console error containing the URN it was trying to navigate you to. Otherwise look at the URL you were redirected to.
> 
>     8. Copy the value of the `?...code=THIS PART` parameter and provide it to DavMail.

If you want to have the class interactive you need to build the davmail with java.fx sdk. If using sdkman you can simply install and use it this way:
```
sdk install java 8.0.382.fx-zulu
sdk use java 8.0.382.fx-zulu
```
Then build in the same terminal davmail, and you won't have the ClassNotFound anymore.

**Comment by mguessan** [comment]
Thanks for your contribution, can you please check my alternative solution ?

**Pull request closed without merging**
