### PR TITLE
Feature/add support for ldap dns format

### PR DESCRIPTION
**Pull request by Levenson**
I am running multiple instances of davmail, and would like to configure
local LDAP (OpenLDAP) with davmails as backends. I came across with two
problems:

1. I cannot pass username 'DOMAIN\user', 'user@domain' or even 'user'
via slapd configuration as those are not a proper DN and slapd rejects
to start.

2. DavMail doesn't escape some special characters in dn attribute when
it prints/sends data which eventually doesn't pass the validation on the
slapd side.

Here are a few patches, which fixed my problems. Please let me know if I
missed something and what else should I do to get them merged. Thanks in
advance.

### CODE REVIEW

**Comment by mguessan** [comment]
Thanks for your feedback, dn authentication and rdn escape available in trunk.

**Comment by Levenson** [comment]
> Thanks for your feedback, dn authentication and rdn escape available in trunk.

@mguessan I see that you moved dn extraction step closer to ldap bind, but it will not work properly. If you send LDAP query first, it will save and try to use uid=xxxx login for other services as well, which is wrong. 

To  reproduce you an:

1. start a new davmail instance with interactive authentification (O365)
2. Send ldap query with uid=xxxx username

The login in auth form will have uid= prefix.

**Comment by mguessan** [comment]
Indeed, fix was incorrect, can you please check again ?

**Comment by Levenson** [comment]
> Indeed, fix was incorrect, can you please check again ?

Unfortunately, LDAP is not working now. If I run, it popups an
authentication form with (uid=xxx) account. Changing the name in the
form doesn't help. If I change it, on my second run it tries popup it
again, but immediately fails and closes.

The problem is because davmail stores username in ExchangeSessionFactor:

davmail.log.20190202-1207:2019-02-02 12:07:01,338 [LdapConnection-41254] INFO  (AbstractConnection.java:158) - FAILED - 127.0.0.1:41254 uid=alexey_abramov@XXXXX
davmail.log.20190202-1208:2019-02-02 12:08:03,175 [LdapConnection-41328] INFO  (AbstractConnection.java:158) - FAILED - 127.0.0.1:41328 uid=alexey_abramov@XXXX
davmail.log.20190202-1208:2019-02-02 12:08:15,242 [LdapConnection-41352] INFO  (AbstractConnection.java:158) - FAILED - 127.0.0.1:41352 uid=alexey_abramov@XXXXX

**Comment by mguessan** [comment]
Ok, that's because I expected a full dn: uid=username,ou=people, not a simple rdn: uid=username.

=> Fixed in trunk

**Pull request closed without merging**
