### PR TITLE
Update URLs in pom.xml to fix a security issue and to avoid redirects

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
See https://lgtm.com/projects/g/mguessan/davmail/ for a list of the current LGTM alerts.

**Comment by mguessan** [comment]
Changed most links from http to https, don't have access to lgtm alerts can you please check ?

**Comment by stweil** [comment]
> Changed most links from http to https, don't have access to lgtm alerts can you please check ?

There remained one link which is still reported and will be fixed by this pull request.

LGTM is down since December 2022. It was replaced by the GitHub CodeQL action which can be enabled for each repository in the security settings and which produces the same report.

**Comment by mguessan** [comment]
Merged in 6.2.0, thanks for your contribution

**Pull request closed without merging**
